services:
  gitlab:
    image: 'mirror.ccs.tencentyun.com/gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'  # 修改为你的域名
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://127.0.0.1'  # 修改为你的域名
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
    ports:
      - '8090:80'      # HTTP
      - '443:443'    # HTTPS
      - '22:22'      # SSH
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge